// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gesture.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_gesture_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_gesture_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_gesture_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_gesture_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gesture_2eproto;
namespace gesture {
class FramePayload;
struct FramePayloadDefaultTypeInternal;
extern FramePayloadDefaultTypeInternal _FramePayload_default_instance_;
class Hand;
struct HandDefaultTypeInternal;
extern HandDefaultTypeInternal _Hand_default_instance_;
class Point;
struct PointDefaultTypeInternal;
extern PointDefaultTypeInternal _Point_default_instance_;
}  // namespace gesture
PROTOBUF_NAMESPACE_OPEN
template<> ::gesture::FramePayload* Arena::CreateMaybeMessage<::gesture::FramePayload>(Arena*);
template<> ::gesture::Hand* Arena::CreateMaybeMessage<::gesture::Hand>(Arena*);
template<> ::gesture::Point* Arena::CreateMaybeMessage<::gesture::Point>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gesture {

// ===================================================================

class Point final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gesture.Point) */ {
 public:
  inline Point() : Point(nullptr) {}
  ~Point() override;
  explicit PROTOBUF_CONSTEXPR Point(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Point(const Point& from);
  Point(Point&& from) noexcept
    : Point() {
    *this = ::std::move(from);
  }

  inline Point& operator=(const Point& from) {
    CopyFrom(from);
    return *this;
  }
  inline Point& operator=(Point&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Point& default_instance() {
    return *internal_default_instance();
  }
  static inline const Point* internal_default_instance() {
    return reinterpret_cast<const Point*>(
               &_Point_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Point& a, Point& b) {
    a.Swap(&b);
  }
  inline void Swap(Point* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Point* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Point* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Point>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Point& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Point& from) {
    Point::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Point* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gesture.Point";
  }
  protected:
  explicit Point(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:gesture.Point)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gesture_2eproto;
};
// -------------------------------------------------------------------

class Hand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gesture.Hand) */ {
 public:
  inline Hand() : Hand(nullptr) {}
  ~Hand() override;
  explicit PROTOBUF_CONSTEXPR Hand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Hand(const Hand& from);
  Hand(Hand&& from) noexcept
    : Hand() {
    *this = ::std::move(from);
  }

  inline Hand& operator=(const Hand& from) {
    CopyFrom(from);
    return *this;
  }
  inline Hand& operator=(Hand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Hand& default_instance() {
    return *internal_default_instance();
  }
  static inline const Hand* internal_default_instance() {
    return reinterpret_cast<const Hand*>(
               &_Hand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Hand& a, Hand& b) {
    a.Swap(&b);
  }
  inline void Swap(Hand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Hand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Hand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Hand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Hand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Hand& from) {
    Hand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Hand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gesture.Hand";
  }
  protected:
  explicit Hand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLandmarksFieldNumber = 6,
    kLabelFieldNumber = 2,
    kBoxMinFieldNumber = 4,
    kBoxMaxFieldNumber = 5,
    kIdFieldNumber = 1,
    kConfidenceFieldNumber = 3,
  };
  // repeated .gesture.Point landmarks = 6;
  int landmarks_size() const;
  private:
  int _internal_landmarks_size() const;
  public:
  void clear_landmarks();
  ::gesture::Point* mutable_landmarks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Point >*
      mutable_landmarks();
  private:
  const ::gesture::Point& _internal_landmarks(int index) const;
  ::gesture::Point* _internal_add_landmarks();
  public:
  const ::gesture::Point& landmarks(int index) const;
  ::gesture::Point* add_landmarks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Point >&
      landmarks() const;

  // string label = 2;
  void clear_label();
  const std::string& label() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_label(ArgT0&& arg0, ArgT... args);
  std::string* mutable_label();
  PROTOBUF_NODISCARD std::string* release_label();
  void set_allocated_label(std::string* label);
  private:
  const std::string& _internal_label() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_label(const std::string& value);
  std::string* _internal_mutable_label();
  public:

  // .gesture.Point box_min = 4;
  bool has_box_min() const;
  private:
  bool _internal_has_box_min() const;
  public:
  void clear_box_min();
  const ::gesture::Point& box_min() const;
  PROTOBUF_NODISCARD ::gesture::Point* release_box_min();
  ::gesture::Point* mutable_box_min();
  void set_allocated_box_min(::gesture::Point* box_min);
  private:
  const ::gesture::Point& _internal_box_min() const;
  ::gesture::Point* _internal_mutable_box_min();
  public:
  void unsafe_arena_set_allocated_box_min(
      ::gesture::Point* box_min);
  ::gesture::Point* unsafe_arena_release_box_min();

  // .gesture.Point box_max = 5;
  bool has_box_max() const;
  private:
  bool _internal_has_box_max() const;
  public:
  void clear_box_max();
  const ::gesture::Point& box_max() const;
  PROTOBUF_NODISCARD ::gesture::Point* release_box_max();
  ::gesture::Point* mutable_box_max();
  void set_allocated_box_max(::gesture::Point* box_max);
  private:
  const ::gesture::Point& _internal_box_max() const;
  ::gesture::Point* _internal_mutable_box_max();
  public:
  void unsafe_arena_set_allocated_box_max(
      ::gesture::Point* box_max);
  ::gesture::Point* unsafe_arena_release_box_max();

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // float confidence = 3;
  void clear_confidence();
  float confidence() const;
  void set_confidence(float value);
  private:
  float _internal_confidence() const;
  void _internal_set_confidence(float value);
  public:

  // @@protoc_insertion_point(class_scope:gesture.Hand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Point > landmarks_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr label_;
    ::gesture::Point* box_min_;
    ::gesture::Point* box_max_;
    int32_t id_;
    float confidence_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gesture_2eproto;
};
// -------------------------------------------------------------------

class FramePayload final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gesture.FramePayload) */ {
 public:
  inline FramePayload() : FramePayload(nullptr) {}
  ~FramePayload() override;
  explicit PROTOBUF_CONSTEXPR FramePayload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FramePayload(const FramePayload& from);
  FramePayload(FramePayload&& from) noexcept
    : FramePayload() {
    *this = ::std::move(from);
  }

  inline FramePayload& operator=(const FramePayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline FramePayload& operator=(FramePayload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FramePayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const FramePayload* internal_default_instance() {
    return reinterpret_cast<const FramePayload*>(
               &_FramePayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FramePayload& a, FramePayload& b) {
    a.Swap(&b);
  }
  inline void Swap(FramePayload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FramePayload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FramePayload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FramePayload>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FramePayload& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FramePayload& from) {
    FramePayload::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FramePayload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gesture.FramePayload";
  }
  protected:
  explicit FramePayload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHandsFieldNumber = 3,
    kTimestampFieldNumber = 1,
    kFrameIdFieldNumber = 2,
  };
  // repeated .gesture.Hand hands = 3;
  int hands_size() const;
  private:
  int _internal_hands_size() const;
  public:
  void clear_hands();
  ::gesture::Hand* mutable_hands(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Hand >*
      mutable_hands();
  private:
  const ::gesture::Hand& _internal_hands(int index) const;
  ::gesture::Hand* _internal_add_hands();
  public:
  const ::gesture::Hand& hands(int index) const;
  ::gesture::Hand* add_hands();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Hand >&
      hands() const;

  // uint64 timestamp = 1;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // int32 frame_id = 2;
  void clear_frame_id();
  int32_t frame_id() const;
  void set_frame_id(int32_t value);
  private:
  int32_t _internal_frame_id() const;
  void _internal_set_frame_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:gesture.FramePayload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Hand > hands_;
    uint64_t timestamp_;
    int32_t frame_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gesture_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Point

// float x = 1;
inline void Point::clear_x() {
  _impl_.x_ = 0;
}
inline float Point::_internal_x() const {
  return _impl_.x_;
}
inline float Point::x() const {
  // @@protoc_insertion_point(field_get:gesture.Point.x)
  return _internal_x();
}
inline void Point::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Point::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:gesture.Point.x)
}

// float y = 2;
inline void Point::clear_y() {
  _impl_.y_ = 0;
}
inline float Point::_internal_y() const {
  return _impl_.y_;
}
inline float Point::y() const {
  // @@protoc_insertion_point(field_get:gesture.Point.y)
  return _internal_y();
}
inline void Point::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Point::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:gesture.Point.y)
}

// -------------------------------------------------------------------

// Hand

// int32 id = 1;
inline void Hand::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Hand::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Hand::id() const {
  // @@protoc_insertion_point(field_get:gesture.Hand.id)
  return _internal_id();
}
inline void Hand::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Hand::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:gesture.Hand.id)
}

// string label = 2;
inline void Hand::clear_label() {
  _impl_.label_.ClearToEmpty();
}
inline const std::string& Hand::label() const {
  // @@protoc_insertion_point(field_get:gesture.Hand.label)
  return _internal_label();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Hand::set_label(ArgT0&& arg0, ArgT... args) {
 
 _impl_.label_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:gesture.Hand.label)
}
inline std::string* Hand::mutable_label() {
  std::string* _s = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:gesture.Hand.label)
  return _s;
}
inline const std::string& Hand::_internal_label() const {
  return _impl_.label_.Get();
}
inline void Hand::_internal_set_label(const std::string& value) {
  
  _impl_.label_.Set(value, GetArenaForAllocation());
}
inline std::string* Hand::_internal_mutable_label() {
  
  return _impl_.label_.Mutable(GetArenaForAllocation());
}
inline std::string* Hand::release_label() {
  // @@protoc_insertion_point(field_release:gesture.Hand.label)
  return _impl_.label_.Release();
}
inline void Hand::set_allocated_label(std::string* label) {
  if (label != nullptr) {
    
  } else {
    
  }
  _impl_.label_.SetAllocated(label, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.label_.IsDefault()) {
    _impl_.label_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:gesture.Hand.label)
}

// float confidence = 3;
inline void Hand::clear_confidence() {
  _impl_.confidence_ = 0;
}
inline float Hand::_internal_confidence() const {
  return _impl_.confidence_;
}
inline float Hand::confidence() const {
  // @@protoc_insertion_point(field_get:gesture.Hand.confidence)
  return _internal_confidence();
}
inline void Hand::_internal_set_confidence(float value) {
  
  _impl_.confidence_ = value;
}
inline void Hand::set_confidence(float value) {
  _internal_set_confidence(value);
  // @@protoc_insertion_point(field_set:gesture.Hand.confidence)
}

// .gesture.Point box_min = 4;
inline bool Hand::_internal_has_box_min() const {
  return this != internal_default_instance() && _impl_.box_min_ != nullptr;
}
inline bool Hand::has_box_min() const {
  return _internal_has_box_min();
}
inline void Hand::clear_box_min() {
  if (GetArenaForAllocation() == nullptr && _impl_.box_min_ != nullptr) {
    delete _impl_.box_min_;
  }
  _impl_.box_min_ = nullptr;
}
inline const ::gesture::Point& Hand::_internal_box_min() const {
  const ::gesture::Point* p = _impl_.box_min_;
  return p != nullptr ? *p : reinterpret_cast<const ::gesture::Point&>(
      ::gesture::_Point_default_instance_);
}
inline const ::gesture::Point& Hand::box_min() const {
  // @@protoc_insertion_point(field_get:gesture.Hand.box_min)
  return _internal_box_min();
}
inline void Hand::unsafe_arena_set_allocated_box_min(
    ::gesture::Point* box_min) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.box_min_);
  }
  _impl_.box_min_ = box_min;
  if (box_min) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gesture.Hand.box_min)
}
inline ::gesture::Point* Hand::release_box_min() {
  
  ::gesture::Point* temp = _impl_.box_min_;
  _impl_.box_min_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::gesture::Point* Hand::unsafe_arena_release_box_min() {
  // @@protoc_insertion_point(field_release:gesture.Hand.box_min)
  
  ::gesture::Point* temp = _impl_.box_min_;
  _impl_.box_min_ = nullptr;
  return temp;
}
inline ::gesture::Point* Hand::_internal_mutable_box_min() {
  
  if (_impl_.box_min_ == nullptr) {
    auto* p = CreateMaybeMessage<::gesture::Point>(GetArenaForAllocation());
    _impl_.box_min_ = p;
  }
  return _impl_.box_min_;
}
inline ::gesture::Point* Hand::mutable_box_min() {
  ::gesture::Point* _msg = _internal_mutable_box_min();
  // @@protoc_insertion_point(field_mutable:gesture.Hand.box_min)
  return _msg;
}
inline void Hand::set_allocated_box_min(::gesture::Point* box_min) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.box_min_;
  }
  if (box_min) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(box_min);
    if (message_arena != submessage_arena) {
      box_min = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, box_min, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.box_min_ = box_min;
  // @@protoc_insertion_point(field_set_allocated:gesture.Hand.box_min)
}

// .gesture.Point box_max = 5;
inline bool Hand::_internal_has_box_max() const {
  return this != internal_default_instance() && _impl_.box_max_ != nullptr;
}
inline bool Hand::has_box_max() const {
  return _internal_has_box_max();
}
inline void Hand::clear_box_max() {
  if (GetArenaForAllocation() == nullptr && _impl_.box_max_ != nullptr) {
    delete _impl_.box_max_;
  }
  _impl_.box_max_ = nullptr;
}
inline const ::gesture::Point& Hand::_internal_box_max() const {
  const ::gesture::Point* p = _impl_.box_max_;
  return p != nullptr ? *p : reinterpret_cast<const ::gesture::Point&>(
      ::gesture::_Point_default_instance_);
}
inline const ::gesture::Point& Hand::box_max() const {
  // @@protoc_insertion_point(field_get:gesture.Hand.box_max)
  return _internal_box_max();
}
inline void Hand::unsafe_arena_set_allocated_box_max(
    ::gesture::Point* box_max) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.box_max_);
  }
  _impl_.box_max_ = box_max;
  if (box_max) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gesture.Hand.box_max)
}
inline ::gesture::Point* Hand::release_box_max() {
  
  ::gesture::Point* temp = _impl_.box_max_;
  _impl_.box_max_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::gesture::Point* Hand::unsafe_arena_release_box_max() {
  // @@protoc_insertion_point(field_release:gesture.Hand.box_max)
  
  ::gesture::Point* temp = _impl_.box_max_;
  _impl_.box_max_ = nullptr;
  return temp;
}
inline ::gesture::Point* Hand::_internal_mutable_box_max() {
  
  if (_impl_.box_max_ == nullptr) {
    auto* p = CreateMaybeMessage<::gesture::Point>(GetArenaForAllocation());
    _impl_.box_max_ = p;
  }
  return _impl_.box_max_;
}
inline ::gesture::Point* Hand::mutable_box_max() {
  ::gesture::Point* _msg = _internal_mutable_box_max();
  // @@protoc_insertion_point(field_mutable:gesture.Hand.box_max)
  return _msg;
}
inline void Hand::set_allocated_box_max(::gesture::Point* box_max) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.box_max_;
  }
  if (box_max) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(box_max);
    if (message_arena != submessage_arena) {
      box_max = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, box_max, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.box_max_ = box_max;
  // @@protoc_insertion_point(field_set_allocated:gesture.Hand.box_max)
}

// repeated .gesture.Point landmarks = 6;
inline int Hand::_internal_landmarks_size() const {
  return _impl_.landmarks_.size();
}
inline int Hand::landmarks_size() const {
  return _internal_landmarks_size();
}
inline void Hand::clear_landmarks() {
  _impl_.landmarks_.Clear();
}
inline ::gesture::Point* Hand::mutable_landmarks(int index) {
  // @@protoc_insertion_point(field_mutable:gesture.Hand.landmarks)
  return _impl_.landmarks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Point >*
Hand::mutable_landmarks() {
  // @@protoc_insertion_point(field_mutable_list:gesture.Hand.landmarks)
  return &_impl_.landmarks_;
}
inline const ::gesture::Point& Hand::_internal_landmarks(int index) const {
  return _impl_.landmarks_.Get(index);
}
inline const ::gesture::Point& Hand::landmarks(int index) const {
  // @@protoc_insertion_point(field_get:gesture.Hand.landmarks)
  return _internal_landmarks(index);
}
inline ::gesture::Point* Hand::_internal_add_landmarks() {
  return _impl_.landmarks_.Add();
}
inline ::gesture::Point* Hand::add_landmarks() {
  ::gesture::Point* _add = _internal_add_landmarks();
  // @@protoc_insertion_point(field_add:gesture.Hand.landmarks)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Point >&
Hand::landmarks() const {
  // @@protoc_insertion_point(field_list:gesture.Hand.landmarks)
  return _impl_.landmarks_;
}

// -------------------------------------------------------------------

// FramePayload

// uint64 timestamp = 1;
inline void FramePayload::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t FramePayload::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t FramePayload::timestamp() const {
  // @@protoc_insertion_point(field_get:gesture.FramePayload.timestamp)
  return _internal_timestamp();
}
inline void FramePayload::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void FramePayload::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:gesture.FramePayload.timestamp)
}

// int32 frame_id = 2;
inline void FramePayload::clear_frame_id() {
  _impl_.frame_id_ = 0;
}
inline int32_t FramePayload::_internal_frame_id() const {
  return _impl_.frame_id_;
}
inline int32_t FramePayload::frame_id() const {
  // @@protoc_insertion_point(field_get:gesture.FramePayload.frame_id)
  return _internal_frame_id();
}
inline void FramePayload::_internal_set_frame_id(int32_t value) {
  
  _impl_.frame_id_ = value;
}
inline void FramePayload::set_frame_id(int32_t value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:gesture.FramePayload.frame_id)
}

// repeated .gesture.Hand hands = 3;
inline int FramePayload::_internal_hands_size() const {
  return _impl_.hands_.size();
}
inline int FramePayload::hands_size() const {
  return _internal_hands_size();
}
inline void FramePayload::clear_hands() {
  _impl_.hands_.Clear();
}
inline ::gesture::Hand* FramePayload::mutable_hands(int index) {
  // @@protoc_insertion_point(field_mutable:gesture.FramePayload.hands)
  return _impl_.hands_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Hand >*
FramePayload::mutable_hands() {
  // @@protoc_insertion_point(field_mutable_list:gesture.FramePayload.hands)
  return &_impl_.hands_;
}
inline const ::gesture::Hand& FramePayload::_internal_hands(int index) const {
  return _impl_.hands_.Get(index);
}
inline const ::gesture::Hand& FramePayload::hands(int index) const {
  // @@protoc_insertion_point(field_get:gesture.FramePayload.hands)
  return _internal_hands(index);
}
inline ::gesture::Hand* FramePayload::_internal_add_hands() {
  return _impl_.hands_.Add();
}
inline ::gesture::Hand* FramePayload::add_hands() {
  ::gesture::Hand* _add = _internal_add_hands();
  // @@protoc_insertion_point(field_add:gesture.FramePayload.hands)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gesture::Hand >&
FramePayload::hands() const {
  // @@protoc_insertion_point(field_list:gesture.FramePayload.hands)
  return _impl_.hands_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gesture

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_gesture_2eproto
